### ISSUE TITLE
[BUG]中文汉化问题

### ISSUE THREAD

**Issue by JIAZIYI007** [Chenzhili1987/86BoxManager-CHS#1]
86box版本兼容性没翻译
waiting被翻成了未响应，应翻译为等待中
麻省理工学院许可证应该加一个（MIT）

**Comment by Chenzhili1987** [comment]
您的第一、二个问题已在[汉化第二版](https://github.com/Chenzhili1987/86BoxManager-CHS/releases/tag/2.0)解决，第三个问题在[汉化第一版](https://github.com/Chenzhili1987/86BoxManager-CHS/releases/tag/1.0)和[汉化第二版](https://github.com/Chenzhili1987/86BoxManager-CHS/releases/tag/2.0)都已解决
